- name: Set firewall rules
  hosts: owy_bms 
  vars:
    - bacnet: 47808
    - ssl_plat: 5011
    - ssl_station: 4911
    - cockpit: 9090
    - gfx_in: 1930
    - gfx_out: 1931
    - radius_in: 1812
    - radius_out: 1813
    - https_re: 8443
    - snmp: 161
    - snmp_trap: 162  
  tasks:
    - name: Set bacnet udp port 
      firewalld:
        port: '{{ bacnet }}/udp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set niagara secure platform port
      firewalld:
        port: '{{ ssl_plat }}/tcp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set secure station tcp port
      firewalld:
        port: '{{ ssl_station }}/tcp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set secure station udp port
      firewalld:
        port: '{{ ssl_station }}/udp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set gfx inbound tcp port
      firewalld:
        port: '{{ gfx_in }}/tcp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set gfx outbound tcp port
      firewalld:
        port: '{{ gfx_out }}/tcp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set radius inbound tcp port
      firewalld:
        port: '{{ radius_in }}/udp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set radius output tcp port
      firewalld:
        port: '{{ radius_out }}/udp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set snmp tcp port
      firewalld:
        port: '{{ snmp }}/tcp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set snmp trap tcp port
      firewalld:
        port: '{{ snmp_trap }}/tcp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set https redirect tcp port
      firewalld:
        port: '{{ https_re }}/tcp'
        permanent: yes
        zone: public
        state: enabled
    - name: Set cockpit tcp port
      firewalld:
        port: '{{ cockpit }}/tcp'
        permanent: yes
        zone: public
        state: enabled
    - name: Reload firewalld
      command: firewall-cmd --reload
